### Sounds Index
GET http://localhost:3000/sounds

### Sounds Create
POST http://localhost:3000/sounds
Content-Type: application/json

{
"name": "Test name",
"overall_rating": 100
}

### Sounds Show
GET http://localhost:3000/sounds/1

### Sounds Update
PATCH http://localhost:3000/sounds/1
Content-Type: application/json

{
"name": "New name",
"overall_rating": 100
}

### Sounds Destroy
DELETE http://localhost:3000/users/1

### Users Index
GET http://localhost:3000/users

### Users Create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
"name": "grace",
"email": "grace@test.com",
"password": "password",
"password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions.json 

### Users Show
GET http://localhost:3000/users/1

### Users Update
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
"name": "New name",
"email": "update@test.com"
}

### Users Destroy
DELETE http://localhost:3000/users/1

### playlists index
GET http:localhost:3000/playlists

### playlists create
POST http:localhost:3000/playlists
Content-Type: application/json

{
  "name" "Playlist 1"
}

### Youtube Search Request 
GET http://localhost:3000/youtube/search?search=rain