@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NTIyODczMjB9.zi98FDBfwDgvI95QZQ5tih-KwU9jCFxyTXuxAnd1h6Q

### Sounds Index
GET http://localhost:3000/sounds

### Sounds Create
POST http://localhost:3000/sounds
Content-Type: application/json

{
"name": "Test name",
"overall_rating": 100
}

### Sounds Show 
GET http://localhost:3000/sounds/1

### Sounds Update
PATCH http://localhost:3000/sounds/1
Content-Type: application/json

{
"name": "New name",
"overall_rating": 100
}

### Sounds Destroy
DELETE http://localhost:3000/users/1

### Users Index
GET http://localhost:3000/users

### Users Create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
"name": "gracee",
"email": "gracee@test.com",
"password": "password",
"password_confirmation": "password"
}

### sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json 

{
  "email": "gracee@test.com",
  "password": "password"
}

### Users Show
GET http://localhost:3000/users/1

### Users Update
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
"name": "New name",
"email": "update@test.com"
}

### Users Destroy
DELETE http://localhost:3000/users/1

### playlists index
GET http://localhost:3000/playlists

### playlists create
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "user_id": 2,
  "name": "Playlist 1",
  "user_rating": 5,
  "youtube_code": "IO5u1m0TsJw"
}

### playlist delete
DELETE http://localhost:3000/playlists/1


### Youtube Search Request 
GET http://localhost:3000/youtube/search?search=rain